### PR TITLE
feat: add new educational sections in english

### PR DESCRIPTION
**Pull request by leesalminen**
This adds the new education sections from https://github.com/galoymoney/earn.

### CODE REVIEW

**Comment by leesalminen** [comment]
https://github.com/GaloyMoney/earn/pull/24
This PR adds a new shell script that processes the source yaml files to the appropriate json structure for the mobile app

https://github.com/GaloyMoney/galoy-mobile/pull/2704
This one adds the English translation for the new sections
I'm not currently able to run this in the simulator but it matches up to the work I did in our fork that does work so should be good? YOLO

https://github.com/GaloyMoney/galoy/pull/3306
This one adds the point allowances to the back end for the new sections

**Comment by UncleSamtoshi** [comment]
Thanks for the pr! Two pieces of feedback:
- Could you instead make the edits to `app/i18n/en/index.ts`? For our translation pipeline, we make all changes to `app/i18n/en/index.ts` and then we run `yarn update-translations` to auto generate `app/i18n/raw-i18n/source/en.json`.
- In order to keep a semantic git history we structure our commits using conventional commits https://www.conventionalcommits.org/en/v1.0.0/

**Comment by leesalminen** [comment]
> Thanks for the pr! Two pieces of feedback:
> 
> * Could you instead make the edits to `app/i18n/en/index.ts`? For our translation pipeline, we make all changes to `app/i18n/en/index.ts` and then we run `yarn update-translations` to auto generate `app/i18n/raw-i18n/source/en.json`.
> * In order to keep a semantic git history we structure our commits using conventional commits https://www.conventionalcommits.org/en/v1.0.0/

done

**Comment by UncleSamtoshi** [comment]
Thanks for making the requested changes! Was your intention to just add the resources to the mobile application or to make them live within the app? Currently the sections are not live and there requires a little more configuration to make it live.

**Comment by leesalminen** [comment]
Yes, I want them visible in the app. I see now I missed adding the new quiz
questions to app/screens/earns-screen/sections.ts...That's different in our
fork, sorry about that! Just pushed a change. I think they should be
showing up now?

**Comment by leesalminen** [comment]
hey @UncleSamtoshi  - I'm finally able to get a simulator for the upstream app and can confirm the new sections are showing up now.

Screenshot_1697549011

**Comment by UncleSamtoshi** [comment]
Thanks for making those changes. Can you run `yarn eslint:fix` in order to get the "Check code" github action to pass? Additionally can you get the tests to a working state? It may require a rebase.

**Comment by UncleSamtoshi** [comment]
I belive this [PR ](https://github.com/GaloyMoney/galoy/pull/3306) needs to be merged before the current pr. I am waiting to merge to approve that pr till I get confirmation from the team that we can effectively prevent fake accounts from getting the increased rewards.

**Comment by leesalminen** [comment]
> Thanks for making those changes. Can you run `yarn eslint:fix` in order to get the "Check code" github action to pass? Additionally can you get the tests to a working state? It may require a rebase.

check-code and tests are now passing.

**Review by UncleSamtoshi — APPROVED** [review]

**Pull request merged**
