### PR TITLE
chore: verify transactions are showing up

### PR DESCRIPTION
**Pull request by nicolasburtey**

### CODE REVIEW

**Comment by nicolasburtey** [comment]
@daviroo not passing for Android

**Comment by nicolasburtey** [comment]
@daviroo it doesn't work for android

**Comment by Extheoisah** [comment]
> @daviroo it doesn't work for android

From my investigation, the issue seems to be because for there's a different accessibility ID for each list item when they're rendered on browser stack. And this is because the elements are only set in the DOM when we fetch the transaction list. 
I think I have a work around for this and I'm working on it.

**Comment by nicolasburtey** [comment]
approved

**Review by Extheoisah — APPROVED** [review]

**Pull request merged**
