### PR TITLE
fix: detect lightning param in bip 21 QR codes

### PR DESCRIPTION
**Pull request by allenwhite**
This PR addresses [this issue](https://github.com/GaloyMoney/galoy-mobile/issues/411), where we do not recognize the lightning param in BIP 21 QR codes. 

In completing this work, I refactored the `validPayment` method, which was getting a little long. The existing logic seemed to initially determine the `paymentType`, and then create the payment response based on this type. I attempted to reflect this approach through some new functions.

To detect the lightning param, I leveraged the `query-string` node module which was already present in the project as a dependency. 

All existing test cases pass, and I added a case for this specific piece of functionality, as well as a couple other cases we were missing.

### CODE REVIEW

**Comment by daviroo** [comment]
Hi @allenwhite.  Thanks for raising the PR.  I tried to scan the example QR code on the linked issue but received the following error.

image

**Comment by allenwhite** [comment]
Good call @bodymindarts - I didn't see any guidelines the the contributing readme, but now that I know, I will clean up the commits.

@daviroo I got that as well, but when I debugged it, it seemed the root cause was because the invoice was expired. Running locally also gave me that error due to the network being testnet. I commented out those checks in `getLightningPayResponse` and saw the expected behavior. I also included the QR in the tests I added to confirm it was working there (since we override `moment.now()`). Let me know if you are seeing something different tho.

**Comment by daviroo** [comment]
> @daviroo I got that as well, but when I debugged it, it seemed the root cause was because the invoice was expired. Running locally also gave me that error due to the network being testnet. I commented out those checks in `getLightningPayResponse` and saw the expected behavior. I also included the QR in the tests I added to confirm it was working there (since we override `moment.now()`). Let me know if you are seeing something different tho.

I think in the case that the lightning invoice has expired we should instead pay to the onchain address.  Can you incorporate this into your change?  Also the commits still don't seem right, did you use rebase?

**Comment by allenwhite** [comment]
Closing in favor of [galoy-client/pull/42](https://github.com/GaloyMoney/galoy-client/pull/42)

**Pull request closed without merging**
