### PR TITLE
chore: no automatic logout on 401

### PR DESCRIPTION
**Pull request by nicolasburtey**

### CODE REVIEW

**Comment by ntheile** [comment]
I tested locally with kratos v0.13 on the backend and it appears to fall into a 403 loop.

**Comment by nicolasburtey** [comment]
> I tested locally with kratos v0.13 on the backend and it appears to fall into a 403 loop.

you mean the 401 issue would be fixed with kratos v0.13? I did try and had a 401 (unless I messed up the version)

**Comment by ntheile** [comment]
with v 0.13 , the whoami endpoint appears to throw a 403 now instead of a 401 when the database is down 
Screen Shot 2023-04-23 at 4 14 40 PM

**Comment by ntheile** [comment]
> with kratos v0.13 , the `whoami` endpoint appears to throw a 403 now instead of a 401 when the database is down Screen Shot 2023-04-23 at 4 14 40 PM

actually sorry, it throws a 403 when both the kratos and postgres containers are down. if just the postgres container is down it still just throws a 401

**Comment by nicolasburtey** [comment]
> > with kratos v0.13 , the `whoami` endpoint appears to throw a 403 now instead of a 401 when the database is down
> 
> actually sorry, it throws a 403 when both the kratos and postgres containers are down. if just the postgres container is down it still just throws a 401

ok that's what I saw. so we should merge my PR? 

until we have clarify on https://github.com/ory/kratos/issues/3250 I think this is the safest way

**Comment by ntheile** [comment]
the modal keeps popping up even after the database comes back up and 200s come back. 

steps to reproduce:
1. Run the mobile app and login
2. Click receive, generate invoice like normal
3. Go back to home page
4. Stop the docker image `kratos-pg`
5. Click receive, generate invoice (modal popup stating 401)
6. Start the docker image `kratos-pg`
7. Click ok on the modal, another one pops up
Screen Shot 2023-04-23 at 4 27 53 PM

**Comment by nicolasburtey** [comment]
> the modal keeps popping up even after the database comes back up and 200 success on a graphql query
> 
> steps to reproduce:
> 
> 1. Run the mobile app and login
> 2. Click receive, generate invoice like normal
> 3. Go back to home page
> 4. Stop the docker image `kratos-pg`
> 5. Click receive, generate invoice (modal popup stating 401)
> 6. Start the docker image `kratos-pg`
> 7. Click ok on the modal, another one pops up again and again
> 
> Screen Shot 2023-04-23 at 4 27 53 PM

oh yeah need to clear the network value... let me do that

**Review by ntheile — APPROVED** [review]

**Pull request merged**
