### PR TITLE
feat: Created account screen

### PR DESCRIPTION
**Pull request by daviroo**
image
image

### CODE REVIEW

**Comment by nicolasburtey** [comment]
I would put Account last

**Comment by nicolasburtey** [comment]
you don't have any phone number showing up? which environment are you testing from?

**Comment by ntheile** [comment]
@daviroo I will need to update the login E2E test. The test search for the logout button on the settings screen to verify the user is logged in. https://github.com/GaloyMoney/galoy-mobile/blob/main/e2e/02-login-flow.e2e.spec.ts#L90 

I could change this to phone number, but want to future proof the test for when we use email. Any suggestions?

**Review by ntheile — APPROVED** [review]

**Comment by ntheile** [comment]
@daviroo If you approve and merge this PR first https://github.com/GaloyMoney/galoy-mobile/pull/711 it ensure the e2e test succeeds when you merge this one.

**Comment by Extheoisah** [comment]
@daviroo All looks good to me. But I think we should move the "Account" button just below "Security" button.

**Comment by daviroo** [comment]
> @daviroo If you approve and merge this PR first #711 it will ensure the e2e test succeeds when you merge this one.

It was my actual phone number so I blanked it out in the screenshot 😆

**Comment by daviroo** [comment]
@nicolasburtey @ntheile I was testing using my actual phone number so I blanked it out in the screenshot 😆

**Review by Extheoisah — APPROVED** [review]

**Pull request merged**
