### PR TITLE
Fix es translations

### PR DESCRIPTION
**Pull request by dolcalmi**
@jrbuhl93 apologies for the messy PR, you just need to check the latest commit changes

- first commit: only sort of the keys in the translation files (no content changes) https://github.com/GaloyMoney/galoy-mobile/commit/d1029f41e5fb01d4f995d963a921c175ffd0f5be 
- Add missing translations, fix some translations https://github.com/GaloyMoney/galoy-mobile/pull/112/commits/029bfb4ba8005569eb9205e810dabb556c1d0b2a

### CODE REVIEW

**Comment by nicolasburtey** [comment]
@dolcalmi I just realized that the earns section with the quiz can't be re-ordered. because the questions/answers in the `"earns": []` array are in the order they are displayed to the user. so going to an alphabetical order here would just completely messed up the education story line

**Comment by dolcalmi** [comment]
> @dolcalmi I just realized that the earns section with the quiz can't be re-ordered. because the questions/answers in the `"earns": []` array are in the order they are displayed to the user. so going to an alphabetical order here would just completely messed up the education story line

are there other sections that needs to be in specific order?

**Comment by jrbuhl93** [comment]
> are there other sections that needs to be in specific order?

I am pretty sure there aren't any other parts of the translations where order matters. As far as I know every other call to translation will just return a string instead of a nested object.

**Comment by dolcalmi** [comment]
ok, just checked the files and arrays are not sorted (there are not keys to sort them)

Current Order of "earns" (meta id): bitcoinWhatIsIt, WhatIsMoney, HowDoesMoneyWork and BitcoinWhySpecial

Also did the check of "content" arrays and they also keep the same order.

**Review by jrbuhl93 — APPROVED** [review]
The translations look good to me. This PR will improve UX a lot.

**Pull request merged**
