### PR TITLE
refactor: changed homescreen transactions text

### PR DESCRIPTION
**Pull request by MaxwellDG**
Fixes issue #2778 @nicolasburtey

### CODE REVIEW

**Comment by nicolasburtey** [comment]
@MaxwellDG can you rename your PR / commit to make it compatible with https://www.conventionalcommits.org/en/v1.0.0/ ?

looks good otherwise

**Comment by MaxwellDG** [comment]
@nicolasburtey Gotcha. I'll keep that format in mind for the future

**Comment by nicolasburtey** [comment]
@MaxwellDG you'll also need to run `yarn update-translations`

**Comment by MaxwellDG** [comment]
@nicolasburtey K done. Trying to figure out why it's not liking my conventional commits still.

**Comment by nicolasburtey** [comment]
> @nicolasburtey K done. Trying to figure out why it's not liking my conventional commits still.

the title of the PR

**Comment by MaxwellDG** [comment]
> > @nicolasburtey K done. Trying to figure out why it's not liking my conventional commits still.
> 
> the title of the PR is what github used when the PR is merged (and when there is several commits, because commits are stashed)

Ahhhh that makes sense. K restarting the checks

**Comment by nicolasburtey** [comment]
merged. thanks!

**Pull request merged**
