### PR TITLE
chore: mark nightly build as prerelease by default

### PR DESCRIPTION
**Pull request by nicolasburtey**
right now nightly build are marked as normal release. if someone were to install the app manually from github, they should now it's not a vetted version and could expect some newly introduced bugs

### CODE REVIEW

**Review by krtk6160 — COMMENTED** [review]
Looks like [`gh release upload`](https://cli.github.com/manual/gh_release_upload) does not accept a `--prerelease` flag.
However, [`gh release create`](https://cli.github.com/manual/gh_release_create) does.

**Comment by nicolasburtey** [comment]
> Looks like [`gh release upload`](https://cli.github.com/manual/gh_release_upload) does not accept a `--prerelease` flag. However, [`gh release create`](https://cli.github.com/manual/gh_release_create) does.

mm I missed that. but there are 2 places where we upload the files. one on iOS and one on android pipeline. so we need a bigger refactor to make this possible because I would imagine we can't call create multiple times

**Comment by nicolasburtey** [comment]
> Looks like [`gh release upload`](https://cli.github.com/manual/gh_release_upload) does not accept a `--prerelease` flag. However, [`gh release create`](https://cli.github.com/manual/gh_release_create) does.

adding the one I missed here: 9873e403f7530ced5dc8665ab1c56198e3484f1b

**Comment by daviroo** [comment]
Closing this but @krtk6160 and I can make sure this is taken into account in the new process.

**Pull request closed without merging**
