### PR TITLE
Feature: show username/BBW address in settings 

### PR DESCRIPTION
**Pull request by Ayush0054**
fixes issue no #873

### CODE REVIEW

**Comment by Ayush0054** [comment]
@nicolasburtey

**Comment by nicolasburtey** [comment]
thanks for your contribution @Ayush0054

**Review by nicolasburtey — APPROVED** [review]

**Comment by Ayush0054** [comment]
thanks for accepting my pr

**Comment by nicolasburtey** [comment]
thanks for making this PR @Ayush0054 !!

**Pull request merged**
