### PR TITLE
Increase input payment font size to 28rem

### PR DESCRIPTION
**Pull request by jrbuhl93**
Fixes issue #99. Thoughts on the new size?
Screenshot_20210731-161639
Screenshot_20210731-162016

### CODE REVIEW

**Comment by nicolasburtey** [comment]
I think it could be even bigger. like 25% to 50% bigger.

**Comment by nicolasburtey** [comment]
maybe use the typo in bold?

**Comment by jrbuhl93** [comment]
The next iteration:
Screenshot_20210801-112958

**Comment by nicolasburtey** [comment]
ok let's go for it for now. I think this is the type of things where we would benefits from the help of the bitcoin design group.

**Pull request merged**
