### PR TITLE
feat: adding onchain stablesats send

### PR DESCRIPTION
**Pull request by nicolasburtey**

### CODE REVIEW

**Review by Extheoisah — COMMENTED** [review]
Looks good to me.... I will test manually tomorrow

**Comment by nicolasburtey** [comment]
> Looks good to me.... I will test manually tomorrow

did some tests and there are some issue with the case where the bitcoin amount is set in the QR code. will debug and put it back as ready when review when I fixed it.

**Comment by nicolasburtey** [comment]
> > Looks good to me.... I will test manually tomorrow
> 
> did some tests and there are some issue with the case where the bitcoin amount is set in the QR code. will debug and put it back as ready when review when I fixed it.

ok fixed and tested, it's working properly now.

**Review by Extheoisah — APPROVED** [review]
Tested it and it works as expected!

**Pull request merged**
